# Generated by Django 2.0.2 on 2018-04-25 05:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField()),
                ('description', models.CharField(max_length=512)),
                ('age_min', models.IntegerField(default=0)),
                ('age_max', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('attendees', models.ManyToManyField(related_name='attendee_accounts', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_host_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('haveIt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=512)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_sent', models.DateTimeField(null=True)),
                ('message', models.CharField(max_length=512)),
                ('reciver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True)),
                ('bio', models.CharField(default='', max_length=500)),
                ('primaryLocation', models.CharField(default='', max_length=200)),
                ('currentLocation', models.CharField(default='', max_length=200)),
                ('hideLocation', models.BooleanField(default=False)),
                ('isBanned', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('rep_message', models.CharField(max_length=512)),
                ('rep_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_account', to=settings.AUTH_USER_MODEL)),
                ('rep_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Event')),
                ('snitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportee_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Event')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='rsvp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Rsvp'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='interests',
            field=models.ManyToManyField(to='API.Interests'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Event'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
