# Generated by Django 2.0.2 on 2018-04-26 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_person_isfemale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='date_sent',
        ),
    ]
